name: On pull request
on:
  push:
    branche-ignore: 'master'
  pull_request:
env:
  TERM: xterm-256color
jobs:
  Tests:

    # Don't run twice for internal PRs from our own repo
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    runs-on: ubuntu-18.04
    strategy:
      matrix:
        target:
          - test-tox-black
          - test-tox-isort
          - test-tox-flake8
          - test-tox-mypy
          - test-tox-python3.7
          - test-tox-python3.8
          - test-tox-python3.9
          - test-tox-python3.10
          - test-tox-python3.11
          
        include:
          - target: test-tox-black
            python-version: |
              3.7
          - target: test-tox-isort
            python-version: |
              3.7
          - target: test-tox-flake8
            python-version: |
              3.7
          - target: test-tox-mypy
            python-version: |
              3.7
          - target: test-tox-python3.7
            python-version: |
              3.7
              3.7
          - target: test-tox-python3.8
            python-version: |
              3.7
              3.8
          - target: test-tox-python3.9
            python-version: |
              3.7
              3.9
          - target: test-tox-python3.10
            python-version: |
              3.7
              3.10
          - target: test-tox-python3.11
            python-version: |
              3.7
              3.11
          
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: |
            ${{ matrix.python-version }}
      - name: Install Tmux
        if: contains(matrix.target, 'python')
        run: |
          sudo apt-get install tmux
      - name: make ${{matrix.target}}
        run: make ${{matrix.target}}
      - name: Check that workingtree is still clean
        run: make check-git-clean



  Build:
    needs: Tests

    # Don't run twice for internal PRs from our own repo
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: make build
        run: make build
      - name: Check that workingtree is still clean
        run: make check-git-clean
