name: On pull request
on:
  pull_request:
  push:
    branches-ignore:
      - 'master'

env:
  TERM: xterm-256color
  UBUNTU_IMAGE: &UBUNTU_IMAGE ubuntu-22.04

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Tests:
    uses: ./.github/workflows/tests.yml
    with:
      runner-image: *UBUNTU_IMAGE
