
name: On push master
on:
  push:
    branches:
      - 'master'
env:
  TERM: xterm-256color
  UBUNTU_IMAGE: &UBUNTU_IMAGE ubuntu-22.04
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:

  Tests:
    uses: ./.github/workflows/tests.yml
    with:
      runner-image: *UBUNTU_IMAGE

  Release:
    needs: Tests
    runs-on: *UBUNTU_IMAGE
    steps:
      - uses: actions/checkout@v2

      - name: Restore pyenv cache
        id: pyenv-cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ needs.Tests.outputs.cache-path }}
          key: ${{ needs.Tests.outputs.cache-key }}
          restore-keys: ${{ needs.Tests.outputs.cache-restore-keys }}

      - name: Setup PYENV
        run: |
          echo "${{ needs.Tests.outputs.cache-path }}/bin" >> "$GITHUB_PATH"
          echo "PYENV_ROOT=${{ needs.Tests.outputs.cache-path }}" >> "$GITHUB_ENV"

      - name: Configure git
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Fetch tags
        run: |
          git fetch --prune --unshallow --tags

      - name: make release
        if: contains(github.event.head_commit.message, '[make release]')
        run: |
          eval "$(pyenv init -)"
          pyenv rehash
          make release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
          CI: "True"

      - name: make prerelease
        if: contains(github.event.head_commit.message, '[make prerelease]')
        run: |
          eval "$(pyenv init -)"
          pyenv rehash
          make prerelease
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
          CI: "True"

      - name: make norelease
        if: |
          ! contains(github.event.head_commit.message, '[make release]')
          && ! contains(github.event.head_commit.message, '[make prerelease]')
        run: |
          eval "$(pyenv init -)"
          pyenv rehash
          make norelease
        env:
          CI: "True"
